/* Front demonstrativo isolado: todos os dados e ações vivem neste navegador.
   Nenhuma chamada à API, autenticação, microfone ou dispositivo da casa. */
(() => {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const paths = {
    orbit:'<circle cx="12" cy="12" r="5"/><ellipse cx="12" cy="12" rx="11" ry="5" transform="rotate(-35 12 12)"/>',
    home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',
    search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
    chat:'<path d="M20 11a8 8 0 0 1-8 8H5l-3 3V11a9 9 0 0 1 18 0Z"/><path d="M7 10h8M7 14h5"/>',
    network:'<circle cx="12" cy="12" r="3"/><circle cx="5" cy="5" r="2"/><circle cx="19" cy="5" r="2"/><circle cx="5" cy="19" r="2"/><circle cx="19" cy="19" r="2"/><path d="m7 7 3 3m4 4 3 3M14 10l3-3M7 17l3-3"/>',
    flow:'<rect x="3" y="3" width="6" height="6" rx="1.5"/><rect x="15" y="15" width="6" height="6" rx="1.5"/><path d="M6 9v7a2 2 0 0 0 2 2h7M15 6h5m-2-2 2 2-2 2"/>',
    wave:'<path d="M3 10v4m4-8v12m5-16v20m5-16v12m4-8v4"/>',
    wallet:'<path d="M20 8V5H5a2 2 0 0 0 0 4h16v11H5a2 2 0 0 1-2-2V7"/><path d="M21 12h-5v5h5M17 14.5h.5"/>',
    plug:'<path d="m8 8 8 8M5 11l6-6 8 8-6 6a5.5 5.5 0 0 1-8-8ZM14 6l3-3m1 7 3-3M6 18l-3 3"/>',
    spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4m-2-2h4"/>',
    sliders:'<path d="M4 6h7m4 0h5M4 12h2m4 0h10M4 18h10m4 0h2"/><circle cx="13" cy="6" r="2"/><circle cx="8" cy="12" r="2"/><circle cx="16" cy="18" r="2"/>',
    settings:'<path d="m9 3-1 3-3 1-2 4 2 2v3l3 2 2 3h4l2-3 3-2v-3l2-2-2-4-3-1-1-3Z"/><circle cx="12" cy="12" r="3"/>',
    chevrons:'<path d="m8 9 4-4 4 4m-8 6 4 4 4-4"/>',
    'arrow-up-right':'<path d="M6 18 18 6M6 6h12v12"/>',
    'arrow-right':'<path d="M4 12h16m-6-6 6 6-6 6"/>',
    shield:'<path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
    sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
    moon:'<path d="M20.8 13.3A9 9 0 0 1 10.7 3.2 9 9 0 1 0 20.8 13.3Z"/>',
    bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',
    expand:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m8 0h5v-5"/>',
    mic:'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8"/>',
    keyboard:'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M6 9h.1M10 9h.1M14 9h.1M18 9h.1M6 12h.1M10 12h.1M14 12h.1M18 12h.1M8 16h8"/>',
    close:'<path d="m6 6 12 12M6 18 18 6"/>',
    menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
    info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',
    check:'<path d="m5 12 4 4L19 6"/>',
    play:'<path d="m8 4 12 8-12 8Z"/>',
    pause:'<path d="M8 5v14M16 5v14"/>',
    refresh:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 6a8 8 0 0 1 13 3M5 15a8 8 0 0 0 13 3"/>',
    plus:'<path d="M12 4v16M4 12h16"/>',
    send:'<path d="m4 4 17 8-17 8 3-8Zm3 8h14"/>',
    stop:'<rect x="5" y="5" width="14" height="14" rx="2"/>',
    file:'<path d="M14 2H5v20h14V7Zm0 0v5h5M8 12h8m-8 4h6"/>',
    clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',
    calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6m10-6v6M3 11h18m-14 4h2m4 0h2"/>',
    mail:'<rect x="2" y="4" width="20" height="16" rx="2"/><path d="m3 5 9 8 9-8"/>',
    light:'<path d="M9 18h6m-6 3h6M8 14a6 6 0 1 1 8 0c-1 1-1 3-1 3H9s0-2-1-3Z"/>',
    temperature:'<path d="M9 15V5a3 3 0 0 1 6 0v10a5 5 0 1 1-6 0ZM12 9v9"/>',
    lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4m-4 5v2"/>',
    music:'<path d="M9 18V5l12-2v13M9 8l12-2"/><ellipse cx="6" cy="18" rx="3" ry="3"/><ellipse cx="18" cy="16" rx="3" ry="3"/>',
    volume:'<path d="M4 9h4l5-5v16l-5-5H4Zm12-1a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',
    trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>',
    download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
    leaf:'<path d="M20 3C5 2 1 9 5 16s16 7 15-13ZM5 20 16 9"/>',
    link:'<path d="m10 14 4-4M8 16l-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m2 1 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0"/>',
  };
  const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.spark}</svg>`;
  function hydrate(root = document) { const nodes=$$('[data-icon]',root);if(root.matches?.('[data-icon]'))nodes.unshift(root);nodes.forEach(el=>{el.innerHTML=icon(el.dataset.icon);}); }
  const storageKey = 'orbita-presenca-prototype-v1';
  let storageWarning = false;
  let saved = {};
  try { saved = JSON.parse(localStorage.getItem(storageKey) || '{}') || {}; } catch { saved = {}; }
  const initialMemories = [
    {id:'m1',title:'Manhãs são para criar',type:'Preferência',body:'Você prefere reservar as primeiras horas do dia para trabalho criativo, sem reuniões.',source:'Conversa de exemplo · 17 set',confidence:'Confirmada por você'},
    {id:'m2',title:'Uma ideia para a Órbita',type:'Ideia',body:'Uma presença que entende o seu ritmo. Interfaces calmas, respostas claras e menos interrupções.',source:'Nota de exemplo · ontem',confidence:'Anotação sua'},
    {id:'m3',title:'Próximos passos do projeto',type:'Projeto',body:'Explorar uma identidade visual mais orgânica e trazer memória e casa para perto da conversa.',source:'Reunião de exemplo · 16 set',confidence:'Fonte disponível'},
    {id:'m4',title:'O ritual do fim do dia',type:'Preferência',body:'Luzes mais quentes, música tranquila e um resumo breve do que ficou para amanhã.',source:'Conversa de exemplo · 15 set',confidence:'Confirmada por você'},
    {id:'m5',title:'A leitura que ficou',type:'Ideia',body:'Ferramentas boas devolvem tempo. Ferramentas excelentes devolvem atenção.',source:'Nota de exemplo · 14 set',confidence:'Anotação sua'},
    {id:'m6',title:'O escritório é seu lugar de foco',type:'Casa',body:'Seu ambiente preferido para criar, com luz da mesa acesa e notificações pausadas.',source:'Preferência de exemplo · 12 set',confidence:'Confirmada por você'},
    {id:'m7',title:'Respostas mais diretas',type:'Preferência',body:'Você gosta de respostas em português, com ações claras e sem excesso de formalidade.',source:'Conversa de exemplo · 10 set',confidence:'Confirmada por você'},
    {id:'m8',title:'Encontros que viram ação',type:'Projeto',body:'Toda reunião deve terminar com uma decisão, um responsável e um próximo passo.',source:'Reunião de exemplo · 9 set',confidence:'Fonte disponível'},
    {id:'m9',title:'A casa ao anoitecer',type:'Casa',body:'A cena Aconchego reúne luz suave na sala e uma playlist tranquila.',source:'Cena de exemplo · 8 set',confidence:'Confirmada por você'},
    {id:'m10',title:'Tempo para aprender',type:'Ideia',body:'Separar um pequeno bloco semanal para testar uma ideia sem compromisso de entrega.',source:'Nota de exemplo · 6 set',confidence:'Anotação sua'},
    {id:'m11',title:'Planejamento sem ruído',type:'Projeto',body:'Escolher três prioridades por dia e deixar o resto em uma lista para depois.',source:'Nota de exemplo · 5 set',confidence:'Anotação sua'},
    {id:'m12',title:'Um domingo mais leve',type:'Preferência',body:'Você prefere sugestões discretas e nenhuma notificação de trabalho no domingo.',source:'Conversa de exemplo · 3 set',confidence:'Confirmada por você'},
  ];
  const state = {
    view:'inicio', theme:saved.theme === 'dark' ? 'dark' : 'light',
    reduced:typeof saved.reduced === 'boolean' ? saved.reduced : matchMedia('(prefers-reduced-motion: reduce)').matches,
    intensity:Number.isFinite(saved.intensity) ? Math.min(100,Math.max(15,saved.intensity)) : 85,
    memories:Array.isArray(saved.memories) && saved.memories.every(m => m && ['id','title','type','body','source','confidence'].every(k => typeof m[k] === 'string')) ? saved.memories : initialMemories,
    routines:[{id:'r1',name:'Um bom começo',description:'O essencial do dia, antes de o mundo pedir sua atenção.',time:'Todos os dias · 08:00',icon:'sun',steps:['Ao começar o dia','Consultar agenda e prioridades','Preparar seu briefing'],active:true},{id:'r2',name:'Hora de mergulhar',description:'Prepare o ambiente e proteja um espaço para criar.',time:'Dias úteis · 09:00',icon:'spark',steps:['No horário de foco','Ajustar a luz do escritório','Pausar interrupções'],active:true},{id:'r3',name:'Desacelerar',description:'Feche os ciclos de hoje e dê espaço para o amanhã.',time:'Todos os dias · 19:00',icon:'moon',steps:['Ao encerrar o trabalho','Reunir pendências do dia','Ativar a cena Aconchego'],active:true}],
    rooms:[{id:'sala',name:'Sala de estar',subtitle:'Um espaço para desacelerar',className:'',light:true,brightness:65,temp:23},{id:'escritorio',name:'Escritório',subtitle:'Seu espaço para criar',className:'office',light:true,brightness:85,temp:22},{id:'quarto',name:'Quarto',subtitle:'Silêncio também é cuidado',className:'bedroom',light:false,brightness:30,temp:24}],
    connections:{calendar:true,mail:true,notion:false,home:true,slack:false,whatsapp:false},
    privacy:true, proactivity:true, memoryFilter:'Tudo', memoryQuery:'', memoryMode:'cards', scene:'',
    approved:null, activities:[], busy:false, chatRun:0, chatTimers:[], demoTimers:[], demoRun:0,
    messages:[{role:'assistant',text:'Oi, Wesley. Que bom ter você por aqui.\n\nPodemos organizar seu dia, retomar uma ideia ou encontrar um pouco de espaço para criar. Por onde começamos?',card:'welcome'}],
    meetingRunning:false, meetingSeconds:0, meetingSummary:false, meetingInterval:null,
    focusSeconds:1500, focusRunning:false, focusDeadline:0, focusInterval:null, focusTrigger:null,
    expenses:[{name:'Mercado da semana',category:'Alimentação',value:286.4,icon:'leaf'},{name:'Internet de casa',category:'Casa',value:129.9,icon:'home'},{name:'Assinaturas e ferramentas',category:'Trabalho',value:89,icon:'plug'}],
    attachment:'', lastAnswer:'',
  };
  const names = {inicio:'Visão geral',conversa:'Conversas',memoria:'Memória',rotinas:'Rotinas',casa:'Minha casa',reunioes:'Reuniões',financas:'Finanças',conexoes:'Conexões',ajustes:'Preferências'};
  const orb = new window.PresenceOrb($('#orb-canvas'));
  const labCanvas=document.createElement('canvas');labCanvas.id='lab-canvas';labCanvas.className='lab-preview';labCanvas.setAttribute('role','img');
  $('.drawer-intro',$('#lab-dialog')).before(labCanvas);
  const labOrb=new window.PresenceOrb(labCanvas);
  const states = window.ORBITA_STATES;
  function persist() {
    try { localStorage.setItem(storageKey,JSON.stringify({theme:state.theme,reduced:state.reduced,intensity:state.intensity,memories:state.memories})); }
    catch { if(!storageWarning){ storageWarning=true; toast('As alterações funcionam nesta sessão, mas o navegador não permitiu salvá-las.'); } }
  }
  let toastTimer;
  function toast(message) { $('#toast-text').textContent=message; $('#toast').classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4700); }
  function updateTheme() { document.documentElement.dataset.theme=state.theme; $('#theme-icon').dataset.icon=state.theme==='dark'?'sun':'moon'; hydrate($('#theme-icon')); [orb,labOrb].forEach(o=>{o.dirty=true;o.schedule();}); persist(); }
  function updateReduced() { document.documentElement.dataset.reduced=String(state.reduced); $('#reduced-toggle').setAttribute('aria-checked',String(state.reduced)); [orb,labOrb].forEach(o=>o.setReduced(state.reduced)); persist(); }
  function updateCounts(){ $('#memory-total-label').textContent=`${state.memories.length} memórias neste universo`;const count=state.routines.filter(r=>r.active).length;$('#routine-count').textContent=count;$('#routine-summary').textContent=`${count} rotinas cuidando do resto`; }
  let researchReply=null;
  document.addEventListener('orbita:research-start',()=>{stopDemo();if(state.busy)stopChat();navigate('inicio');setOrb('searching');});
  document.addEventListener('orbita:research-update',()=>{if(researchReply){researchReply.researchHTML=window.orbitaResearch.chatHTML();renderMessages();}});
  document.addEventListener('orbita:research-complete',()=>{if(!state.busy&&orb.state==='searching'){setOrb('success');later(()=>{if(orb.state==='success')setOrb('idle');},1900);}});
  document.addEventListener('orbita:research-close',()=>{if(orb.state==='searching')setOrb('idle');});
  function setOrb(mode) {
    orb.setState(mode); labOrb.setState(mode); const cfg=states[mode];
    document.body.dataset.orbState=mode;
    $('#state-label').textContent=cfg.status; $('#orb-title').textContent=cfg.title;
    $('#orb-description').textContent=cfg.description; $('#orb-tag-label').textContent=mode==='idle'?'Tudo no seu ritmo':cfg.label;
    $('#focus-state').textContent=cfg.status.toUpperCase(); $('#state-note').textContent=cfg.note;
    $$('.state-button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.state===mode)));
  }
  function stopDemo() { state.demoRun++; state.demoTimers.forEach(clearTimeout); state.demoTimers=[]; }
  function later(fn,delay) { const run=state.demoRun; state.demoTimers.push(setTimeout(()=>{if(run===state.demoRun)fn();},delay)); }
  function log(title,detail,ico='check') {state.activities.unshift({title,detail,icon:ico}); if($('#activity-dialog').open) renderActivity();}
  function viewHeading(eyebrow,title,subtitle,action='') { return `<div class="view-heading"><div><span class="eyebrow">${eyebrow}</span><h1>${title}<span class="mint-period">.</span></h1><p>${subtitle}</p></div>${action}</div>`; }
  const button=(text,action,ico='plus',type='primary')=>`<button class="button ${type}" data-action="${action}">${icon(ico)}${text}</button>`;
  function navigate(view){ if(!names[view])view='inicio'; if(location.hash!==`#${view}`)location.hash=view; else renderView(view); }
  function renderView(view) {
    if(!names[view])view='inicio'; state.view=view;
    $$('.view').forEach(el=>el.hidden=el.id!==`view-${view}`);
    $$('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===view); if(el.dataset.view===view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});
    $('#breadcrumb').textContent=names[view]; document.title=`${names[view]} · Órbita Presença`;
    closeMenu(); const renderers={conversa:renderChat,memoria:renderMemory,rotinas:renderRoutines,casa:renderHome,reunioes:renderMeetings,financas:renderFinance,conexoes:renderConnections,ajustes:renderSettings};
    renderers[view]?.(); hydrate($(`#view-${view}`));
    window.scrollTo({top:0,behavior:'instant'});
    if(view==='inicio'){orb.resize();updateCounts();}
  }
  function closeMenu(){$('#sidebar').classList.remove('open');$('#mobile-scrim').classList.remove('open');}
  function openDialog(title,content) {const dialog=$('#detail-dialog');$('#dialog-content').innerHTML=`<h2 id="dialog-title">${title}</h2>${content}`;hydrate(dialog); if(!dialog.open)dialog.showModal();}
  function closeDialog(){$('#detail-dialog').close();}

  function renderChat() {
    $('#view-conversa').innerHTML=viewHeading('UM PENSAMENTO PUXA O OUTRO','Vamos conversar','Uma conversa que pode virar memória, plano ou próximo passo.')+`<div class="chat-layout"><aside class="panel chat-history">${button('Nova conversa','new-chat','plus','secondary full-width')}<div class="panel-label">ESPAÇOS DE CONVERSA</div><button class="history-item active" data-action="current-chat">${icon('chat')}Seu momento de hoje</button><button class="history-item" data-action="project-chat">${icon('chat')}Uma nova Órbita</button><button class="history-item" data-action="home-chat">${icon('chat')}A casa no meu ritmo</button><div class="notice">Conversas e respostas demonstrativas. Nenhum modelo de IA está conectado.</div></aside><article class="panel chat-main"><div class="chat-top"><span class="mini-orb"></span><div><h2>Uma presença para pensar junto</h2><p>Seu contexto. Seu ritmo. Sua escolha.</p></div><span class="tag green">DEMO INTERATIVA</span></div><div class="chat-messages" id="chat-messages" role="log" aria-label="Conversa demonstrativa" aria-live="polite"></div><form class="composer" id="chat-form"><div id="attachment-slot"></div><div class="composer-inner"><button type="button" class="icon-button" data-action="attach" aria-label="Anexar arquivo à demonstração">${icon('plus')}</button><textarea id="chat-input" rows="1" maxlength="3000" aria-label="Mensagem para a Órbita" placeholder="O que está passando pela sua cabeça?"></textarea><button type="button" class="icon-button" data-action="voice" aria-label="Experimentar conversa por voz">${icon('mic')}</button><button type="submit" class="icon-button send-button" id="chat-send" aria-label="${state.busy?'Parar resposta':'Enviar mensagem'}">${icon(state.busy?'stop':'send')}</button></div><div class="composer-hint"><span>Enter para enviar · Shift + Enter para uma nova linha</span><span>Respostas de exemplo</span></div></form></article></div>`;
    renderMessages(); renderAttachment();
    $('#chat-form').addEventListener('submit',e=>{e.preventDefault();if(state.busy){stopChat();return;}const input=$('#chat-input');const text=input.value.trim();if(text||state.attachment){sendMessage(text||`Veja o arquivo ${state.attachment}`);input.value='';}});
    $('#chat-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#chat-form').requestSubmit();}});
  }
  function renderMessages() {
    const logEl=$('#chat-messages');if(!logEl)return;
    logEl.innerHTML=state.messages.map(m=>`<div class="message ${m.role}">${m.role==='assistant'?'<span class="mini-orb"></span>':''}<div class="message-body"><div class="message-author">${m.role==='assistant'?'Órbita · cenário demonstrativo':'Você'}${m.partial?' · interrompida':''}</div>${m.attachment?`<div class="attachment-chip">${icon('file')}${escape(m.attachment)}</div>`:''}<p>${escape(m.text)}</p>${m.typing?'<span class="typing-dot"></span><span class="typing-dot"></span><span class="typing-dot"></span>':''}${m.card==='welcome'?'<div class="chat-suggestions"><button data-prompt="Como está meu dia?">Organizar meu dia</button><button data-prompt="Vamos retomar minha ideia para a Órbita">Retomar uma ideia</button><button data-prompt="Quero um momento de foco">Criar espaço para focar</button></div>':''}${m.card==='briefing'?'<div class="message-assistant-card"><strong>Seu dia, com respiro</strong><p>14:00 · Alinhamento de projeto\n16:00 · Espaço para criar\nUma prioridade: explorar a nova identidade da Órbita.</p><button class="text-button" data-action="focus">Proteger meu momento '+icon('arrow-right')+'</button></div>':''}${m.card==='approval'?'<div class="message-assistant-card"><strong>Uma ação esperando sua decisão</strong><p>Preparei um convite de exemplo. Você pode revisar cada detalhe antes de aprovar.</p><button class="text-button" data-action="activity">Revisar a proposta '+icon('arrow-right')+'</button></div>':''}${m.card==='memory'?'<div class="message-assistant-card"><strong>De onde veio essa conexão</strong><p>“Uma ideia para a Órbita” + “Próximos passos do projeto”. Memórias demonstrativas, com fonte visível.</p><button class="text-button" data-goto="memoria">Explorar memórias '+icon('arrow-right')+'</button></div>':''}${m.role==='assistant'&&!m.typing&&m.card!=='welcome'&&m.text?'<div class="chat-suggestions"><button data-action="save-answer">Guardar como memória</button><button data-action="read-answer">Ouvir com a voz do navegador</button></div>':''}</div></div>`).join('');
    $$('.message',logEl).forEach((el,index)=>{const message=state.messages[index];if(message.card==='research')$('.message-body',el).insertAdjacentHTML('beforeend',message.researchHTML||window.orbitaResearch.chatHTML());});
    const welcome=$('.chat-suggestions',logEl);if(state.messages[0]?.card==='welcome'&&welcome&&!$('[data-research-prompt]',welcome))welcome.insertAdjacentHTML('beforeend','<button data-research-prompt data-prompt="Pesquise interfaces 3D no navegador">Pesquisar com fontes</button>');
    logEl.scrollTop=logEl.scrollHeight;
    if($('#chat-send')){ $('#chat-send').innerHTML=icon(state.busy?'stop':'send');$('#chat-send').setAttribute('aria-label',state.busy?'Parar resposta':'Enviar mensagem'); }
  }
  function demoAnswer(text){const lower=text.toLocaleLowerCase('pt-BR');if(/(agenda|meu dia|bom dia|organizar)/.test(lower))return{text:'Vamos abrir um pouco de espaço no seu dia. Neste cenário, você tem dois compromissos e pode reservar um intervalo para explorar suas ideias. Separei o essencial abaixo.',card:'briefing'};if(/(email|e-mail|convite|agendar|marcar)/.test(lower))return{text:'Posso ajudar a transformar isso em um próximo passo. Neste exemplo, preparei um convite para uma conversa sobre o projeto. Ele fica esperando sua revisão; nada será enviado.',card:'approval'};if(/(ideia|mem[oó]ria|[oó]rbita|projeto)/.test(lower))return{text:'Há uma conexão interessante aqui: você anotou que uma boa ferramenta deve devolver atenção, e o projeto de hoje fala justamente sobre uma interface mais calma. Podemos partir disso para explorar uma presença mais orgânica, com menos interrupções.',card:'memory'};if(/(foco|concentr|pausa|cansad)/.test(lower))return{text:'Podemos começar pequeno: um momento de 25 minutos, uma única prioridade e nenhuma pressa. O modo foco deste protótipo tem um temporizador real, que você pode pausar e retomar. Abra “Modo foco” para experimentar.'};if(/(casa|luz|sala)/.test(lower))return{text:'Uma casa pode acompanhar seu ritmo. Na tela Minha casa, experimente as cenas Criar, Aconchego e Boa noite. As luzes e os controles mudam apenas nesta demonstração; nenhum dispositivo real será acionado.'};if(/(finan|gast|conta|dinheiro)/.test(lower))return{text:'Na tela Finanças, você encontra um cenário de exemplo com saldo, despesas e categorias. Experimente registrar um gasto para ver os totais mudarem. Os valores são fictícios e não vêm de nenhuma conta bancária.'};if(/(arquivo|anexo)/.test(lower))return{text:'O anexo aparece na conversa para demonstrar a experiência visual. Este protótipo não lê nem envia o conteúdo do arquivo. Na versão integrada, este seria o ponto de extrair informações e mostrar a origem de cada resposta.'};return{text:'Sua mensagem entrou no protótipo. Aqui, as respostas são roteiros de demonstração, sem um modelo de IA conectado.\n\nPara explorar a experiência, experimente “como está meu dia?”, “retomar uma ideia”, “preparar um convite” ou “quero um momento de foco”.'};}
  function sendMessage(text){
    if(state.busy)return; stopDemo(); state.busy=true; const run=++state.chatRun;
    state.messages.push({role:'user',text,attachment:state.attachment});state.attachment='';renderAttachment();
    const isResearch=/(pesquis|busc|fontes|refer[eê]ncia)/i.test(text);
    const answer=isResearch?{text:'Neste exemplo de pesquisa, reuni três referências oficiais sobre interfaces 3D no navegador: MDN, Three.js e Khronos. Os cards mostram a origem e permitem abrir cada documento.\n\nEsta é uma demonstração visual: os links são reais, mas a descoberta e esta resposta são roteirizadas. Uma busca conectada poderá usar a mesma experiência para o tema que você solicitar.',card:'research'}:demoAnswer(text);
    const reply={role:'assistant',text:'',typing:true,card:isResearch?'research':undefined};state.messages.push(reply);
    if(isResearch){researchReply=reply;window.orbitaResearch.start();setOrb('searching');}else setOrb('thinking');renderMessages();
    const wait=setTimeout(()=>{
      if(run!==state.chatRun)return;reply.typing=false;setOrb('speaking');let cursor=0;
      const stream=setInterval(()=>{
        if(run!==state.chatRun){clearInterval(stream);return;}
        cursor+=7;reply.text=answer.text.slice(0,cursor);renderMessages();
        if(cursor>=answer.text.length){clearInterval(stream);reply.card=answer.card;state.busy=false;state.lastAnswer=answer.text;if(researchReply===reply)researchReply=null;setOrb(answer.card==='approval'?'attention':'idle');renderMessages();}
      },24);state.chatTimers.push(stream);
    },isResearch?3300:850);state.chatTimers.push(wait);renderMessages();
  }
  function stopChat(){state.chatRun++;state.chatTimers.forEach(clearTimeout);state.chatTimers.forEach(clearInterval);state.chatTimers=[];state.busy=false;if(researchReply){window.orbitaResearch.stop();researchReply=null;}const last=state.messages.at(-1);if(last?.role==='assistant'&&(last.typing||last.text)){last.typing=false;last.partial=true;if(!last.text)last.text='Resposta interrompida. Podemos recomeçar quando você quiser.';}setOrb('idle');renderMessages();}
  function renderAttachment(){const slot=$('#attachment-slot');if(slot)slot.innerHTML=state.attachment?`<div class="attachment-chip">${icon('file')}${escape(state.attachment)}<button type="button" class="icon-button" data-action="remove-attachment" aria-label="Remover anexo">${icon('close')}</button></div>`:'';}

  function renderMemory(){
    $('#view-memoria').innerHTML=viewHeading('IDEIAS QUE SE ENCONTRAM','Sua segunda memória','Mais do que guardar. Conectar o que você sabe ao que está vivendo.',button('Guardar uma ideia','add-memory'))+`<div class="memory-banner">${icon('spark')}<div><h3>Uma conexão esperando por você</h3><p>Sua ideia de uma interface calma pode ser o começo do próximo projeto.</p></div>${button('Explorar conexão','memory-recall','arrow-right','secondary')}</div><div class="section-heading"><div class="filter-bar">${['Tudo','Ideia','Preferência','Projeto','Casa'].map(t=>`<button class="filter-chip ${state.memoryFilter===t?'active':''}" data-memory-filter="${t}">${t==='Tudo'?'Todas':t}</button>`).join('')}</div><button class="text-button" data-action="memory-view">${icon(state.memoryMode==='cards'?'network':'file')}${state.memoryMode==='cards'?'Ver conexões':'Ver cartões'}</button></div><label class="field" style="margin-top:0"><span class="panel-label">ENCONTRE UMA LEMBRANÇA</span><input id="memory-search" type="search" placeholder="Busque por uma ideia, preferência ou projeto..." value="${escape(state.memoryQuery)}"></label><div id="memory-results"></div>`;
    $('#memory-search').addEventListener('input',e=>{state.memoryQuery=e.target.value;renderMemoryResults();});renderMemoryResults();
  }
  function renderMemoryResults(){
    const memories=state.memories.filter(m=>(state.memoryFilter==='Tudo'||m.type===state.memoryFilter)&&`${m.title} ${m.body}`.toLocaleLowerCase('pt-BR').includes(state.memoryQuery.toLocaleLowerCase('pt-BR')));
    if(state.memoryMode==='graph'){
      const nodes=memories.slice(0,8);$('#memory-results').innerHTML=`<div class="panel"><div class="memory-graph"><svg viewBox="0 0 700 330" role="img" aria-label="Mapa ilustrativo das memórias filtradas conectadas ao seu contexto">${nodes.map((m,i)=>{const a=i/nodes.length*Math.PI*2,x=350+Math.cos(a)*225,y=165+Math.sin(a)*112;return `<line x1="350" y1="165" x2="${x}" y2="${y}"/><circle cx="${x}" cy="${y}" r="16"/><text x="${x}" y="${y+32}" text-anchor="middle">${escape(m.title.slice(0,27))}</text>`;}).join('')}<circle class="core-node" cx="350" cy="165" r="42"/><text class="core-label" x="350" y="170" text-anchor="middle">você.</text></svg></div><p class="description">Mapa ilustrativo de ${nodes.length} memórias do filtro atual. Selecione uma abaixo para consultar ou editar a fonte.</p>${nodes.map(m=>`<button class="filter-chip" data-memory="${m.id}">${escape(m.title)}</button>`).join(' ')}</div>`;return;
    }
    $('#memory-results').innerHTML=memories.length?`<div class="three-columns">${memories.map(m=>`<button class="panel memory-card" data-memory="${m.id}"><span class="tag ${m.type==='Ideia'?'purple-tag':m.type==='Casa'?'orange-tag':'green'}">${escape(m.type)}</span><h3>${escape(m.title)}</h3><p>${escape(m.body)}</p><span class="memory-meta"><span>${escape(m.source)}</span>${icon('arrow-up-right')}</span></button>`).join('')}</div>`:'<div class="panel empty-state">Nenhuma memória por aqui ainda. Experimente outro termo ou guarde uma ideia.</div>';
  }
  function memoryForm(memory){openDialog(memory?'Uma memória, do seu jeito.':'Uma ideia para guardar.',`<form id="memory-form"><label class="field">Título<input name="title" required maxlength="90" value="${escape(memory?.title||'')}" placeholder="O que vale lembrar?"></label><label class="field">Tipo<select name="type">${['Ideia','Preferência','Projeto','Casa'].map(t=>`<option ${memory?.type===t?'selected':''}>${t}</option>`).join('')}</select></label><label class="field">Sua anotação<textarea name="body" required maxlength="2000" placeholder="Conte um pouco mais...">${escape(memory?.body||'')}</textarea></label>${memory?`<div class="notice">Fonte: ${escape(memory.source)}<br>Confiança: ${escape(memory.confidence)}<br>Você pode corrigir ou esquecer esta memória a qualquer momento.</div>`:''}<div class="form-actions">${memory?`<button type="button" class="button danger" data-delete-memory="${memory.id}">${icon('trash')}Esquecer</button>`:''}<button type="button" class="button secondary" data-action="close-dialog">Cancelar</button><button class="button primary" type="submit">${icon('check')}Guardar memória</button></div></form>`);
    $('#memory-form').addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.target);const title=form.get('title').trim(),body=form.get('body').trim();if(!title||!body){toast('Escreva um título e uma anotação.');return;}if(memory){memory.title=title;memory.body=body;memory.type=form.get('type');memory.confidence='Confirmada por você';}else state.memories.unshift({id:crypto.randomUUID(),title,body,type:form.get('type'),source:'Criada neste protótipo',confidence:'Confirmada por você'});persist();updateCounts();closeDialog();if(state.view==='memoria')renderMemory();toast('Memória guardada neste navegador.');log('Uma ideia ganhou espaço',title,'network');});
  }

  function renderRoutines(){
    $('#view-rotinas').innerHTML=viewHeading('O COTIDIANO PODE SER MAIS LEVE','Pequenos rituais, grandes respiros','Você escolhe a intenção. A Órbita cuida da sequência.',button('Criar rotina','add-routine'))+`<div class="three-columns">${state.routines.map(r=>`<article class="panel routine-card"><div class="routine-top"><span class="quick-icon ${r.icon==='sun'?'peach-bg':r.icon==='moon'?'lavender-bg':'mint-bg'}">${icon(r.icon)}</span><button class="switch" role="switch" aria-checked="${r.active}" aria-label="Ativar rotina ${escape(r.name)}" data-routine-toggle="${r.id}"></button></div><h3>${escape(r.name)}</h3><p>${escape(r.description)}</p><div class="routine-flow">${r.steps.map((s,i)=>`${i?'<div class="flow-connector"></div>':''}<div class="flow-step"><span>${icon(['clock','network','check'][i]||'check')}</span>${escape(s)}</div>`).join('')}</div><div class="routine-bottom"><span>${escape(r.time)}</span><button class="text-button" data-run-routine="${r.id}" ${r.active?'':'disabled'}>Testar ${icon('play')}</button></div></article>`).join('')}</div><div class="notice">Ative, pause ou teste as rotinas. Nesta proposta, os passos são simulados e não alteram agenda, notificações ou dispositivos.</div>`;
  }
  function routineForm(){openDialog('Um ritual que combina com você.',`<form id="routine-form"><label class="field">Nome da rotina<input name="name" required maxlength="60" placeholder="Ex.: Minha pausa da tarde"></label><label class="field">Quando começa?<input name="time" type="time" required value="15:00"></label><label class="field">Qual é a intenção?<textarea name="description" required maxlength="300" placeholder="Uma pausa, um lembrete, um ambiente melhor..."></textarea></label><label class="field">O que acontece depois?<select name="effect"><option>Preparar um lembrete gentil</option><option>Reservar um momento de foco</option><option>Sugerir uma cena para a casa</option></select></label><div class="form-actions"><button type="button" class="button secondary" data-action="close-dialog">Cancelar</button><button type="submit" class="button primary">Criar rotina de exemplo</button></div></form>`);$('#routine-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const name=f.get('name').trim(),description=f.get('description').trim();if(!name||!description)return;state.routines.push({id:crypto.randomUUID(),name,description,time:`Todos os dias · ${f.get('time')}`,icon:'spark',steps:[`Às ${f.get('time')}`,'Considerar seu contexto',f.get('effect')],active:true});closeDialog();renderRoutines();updateCounts();toast('Nova rotina adicionada à demonstração.');});}
  function runRoutine(id){const routine=state.routines.find(r=>r.id===id);if(!routine?.active)return;openDialog(`Experimentando: ${escape(routine.name)}`,`<p class="dialog-description">Veja como a Órbita comunica cada etapa. Esta execução é apenas visual.</p><div id="routine-progress" class="detail-list">${routine.steps.map((s,i)=>`<div id="routine-step-${i}"><span>${icon('clock')}</span><div><strong>${escape(s)}</strong><p>Aguardando</p></div></div>`).join('')}</div><div class="form-actions"><button class="button secondary" data-action="close-dialog">Fechar</button></div>`);stopDemo();setOrb('connecting');routine.steps.forEach((s,i)=>later(()=>{const row=$(`#routine-step-${i}`);if(row){$('span',row).innerHTML=icon('check');$('p',row).textContent='Etapa demonstrada';}if(i===routine.steps.length-1){setOrb('success');log('Rotina testada',`${routine.name} · apenas nesta demonstração`,'flow');toast('Fluxo demonstrado. Nenhuma ação real foi executada.');}},700+i*1100));}

  function renderHome(){
    $('#view-casa').innerHTML=viewHeading('TECNOLOGIA QUE SABE ACOLHER','Uma casa no seu ritmo','Ambientes que acompanham seu momento. Você continua no controle.',`<span class="tag green">${icon('shield')}CASA DEMONSTRATIVA</span>`)+`<div class="three-columns">${state.rooms.map(r=>`<article class="panel room-card"><div class="room-visual ${r.className}"><div class="room-illustration" aria-hidden="true"></div></div><div class="room-body"><div class="room-label"><h3>${r.name}</h3><span class="tag">${r.temp} °C</span></div><p>${r.subtitle}</p><div class="room-controls"><span>Luz ${r.light?'acesa':'apagada'}</span><button class="switch" role="switch" aria-checked="${r.light}" aria-label="Luz da ${r.name}" data-room-light="${r.id}"></button></div><div class="room-controls"><label for="brightness-${r.id}">Intensidade</label><output id="output-${r.id}">${r.brightness}%</output></div><input id="brightness-${r.id}" type="range" data-brightness="${r.id}" min="0" max="100" value="${r.brightness}" aria-label="Intensidade da luz ${r.name}" ${r.light?'':'disabled'}></div></article>`).join('')}</div><article class="panel" style="margin-top:22px"><span class="eyebrow">CENAS PARA O SEU MOMENTO</span><h2 style="margin-top:8px">Como você quer se sentir?</h2><div class="scene-grid">${[['criar','spark','Criar'],['aconchego','sun','Aconchego'],['noite','moon','Boa noite']].map(([id,ico,label])=>`<button class="scene-button ${state.scene===id?'active':''}" data-scene="${id}">${icon(ico)}${label}</button>`).join('')}</div><p class="description" style="margin-bottom:0">As cenas ajustam os controles deste protótipo. Nenhuma conexão com Home Assistant ou dispositivos reais está ativa.</p></article><div class="two-columns" style="margin-top:22px"><article class="panel"><h2>Objetos também têm memória</h2><p class="description">Uma proposta para encontrar o que ficou fora de vista.</p>${button('Onde deixei minha chave?','find-object','search','secondary')}</article><article class="panel"><h2>O controle continua seu</h2><p class="description">Portas, alarmes e outras ações sensíveis pedem uma confirmação clara.</p>${button('Ver uma aprovação','door-approval','lock','secondary')}</article></div>`;
  }
  function applyScene(id){state.scene=id;state.rooms.forEach((r,i)=>{r.light=id==='criar'?i===1:id==='aconchego'?i===0:false;r.brightness=id==='criar'?85:id==='aconchego'?35:0;});renderHome();setOrb('success');toast(`Cena ${id==='criar'?'Criar':id==='aconchego'?'Aconchego':'Boa noite'} aplicada apenas à demonstração.`);log('O ambiente mudou de ritmo','Cena demonstrativa aplicada aos controles locais.','home');}

  const meetingLines=[['Wesley','Vamos buscar uma experiência mais calma, que deixe a presença da Órbita no centro.'],['Marina','Podemos organizar a navegação por momentos, em vez de mostrar todos os painéis juntos.'],['Wesley','E quero enxergar claramente quando ela está ouvindo, pensando ou esperando minha decisão.'],['Marina','Então o próximo passo é experimentar os estados e validar a proposta no celular.']];
  function renderMeetings(){
    $('#view-reunioes').innerHTML=viewHeading('ESTEJA NA CONVERSA','O que foi dito ganha um depois','Uma escuta atenta. Decisões claras. Próximos passos que não se perdem.')+`<div class="two-columns"><article class="panel meeting-live"><span class="tag">DEMONSTRAÇÃO</span><span class="eyebrow">SUA PRÓXIMA CONVERSA</span><h2>Alinhamento de projeto</h2><p>Uma nova experiência para a Órbita</p><div class="waveform ${state.meetingRunning?'running':''}" id="meeting-wave">${Array.from({length:40},(_,i)=>`<i style="--h:${12+Math.sin(i*.7)**2*45}px;--delay:${i*-.09}s"></i>`).join('')}</div><p id="meeting-time">${formatTime(state.meetingSeconds)}</p><button class="button" data-action="meeting-toggle" id="meeting-toggle">${icon(state.meetingRunning?'stop':'play')}${state.meetingRunning?'Encerrar demonstração':'Simular uma reunião'}</button><p style="margin-top:15px;font-size:10px">Roteiro de exemplo. Sem gravação de microfone.</p></article><article class="panel"><div class="section-heading"><h2>Palavras que ficam</h2><span class="tag">TRANSCRIÇÃO DEMO</span></div><div class="transcript" id="meeting-transcript"></div></article></div><div id="meeting-summary-slot"></div><article class="panel" style="margin-top:22px"><h2>Uma conversa anterior</h2><div class="list-row"><span class="quick-icon lavender-bg">${icon('wave')}</span><div><strong>Explorando a nova identidade</strong><small>16 de setembro · 32 min · 2 participantes · Dados de exemplo</small></div><button class="text-button" data-action="meeting-summary">Ver resumo ${icon('arrow-right')}</button></div></article>`;
    renderTranscript();if(state.meetingSummary)renderMeetingSummary();
  }
  function renderTranscript(){const target=$('#meeting-transcript');if(!target)return;const count=Math.min(4,Math.floor(state.meetingSeconds/3));target.innerHTML=count?meetingLines.slice(0,count).map(([speaker,text],i)=>`<div class="transcript-row"><strong>${speaker}<time>00:${String((i+1)*3).padStart(2,'0')}</time></strong>${text}</div>`).join(''):'<div class="empty-state">Inicie a demonstração para ver a conversa se transformar em contexto.</div>';target.scrollTop=target.scrollHeight;}
  function toggleMeeting(){if(state.meetingRunning){clearInterval(state.meetingInterval);state.meetingRunning=false;state.meetingSummary=true;setOrb('success');renderMeetings();log('Reunião demonstrativa encerrada','Resumo e próximos passos preparados a partir do roteiro.','wave');return;}state.meetingSeconds=0;state.meetingSummary=false;state.meetingRunning=true;setOrb('listening');renderMeetings();state.meetingInterval=setInterval(()=>{state.meetingSeconds++;if($('#meeting-time'))$('#meeting-time').textContent=formatTime(state.meetingSeconds);renderTranscript();if(state.meetingSeconds>=15)toggleMeeting();},1000);}
  function renderMeetingSummary(){const slot=$('#meeting-summary-slot');if(!slot)return;slot.innerHTML=`<article class="panel meeting-summary"><span class="tag green">RESUMO DO ROTEIRO DE EXEMPLO</span><h2 style="margin-top:14px">Uma interface que devolve atenção</h2><p class="description">A direção escolhida no roteiro combina navegação por contexto, núcleo expressivo e uma experiência mais silenciosa.</p><ul><li>Explorar uma identidade orgânica e uma paleta mineral.</li><li>Diferenciar escuta, pensamento, fala e aprovação por movimento.</li><li>Validar o protótipo em telas pequenas antes da integração.</li></ul>${button('Guardar decisões na memória','save-meeting','network','secondary')}</article>`;}

  function renderFinance(){const total=state.expenses.reduce((sum,e)=>sum+e.value,0);const brl=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});$('#view-financas').innerHTML=viewHeading('CLAREZA PARA ESCOLHER','Seu dinheiro, em perspectiva','Um olhar simples para as finanças. Todos os valores abaixo são fictícios.',button('Registrar gasto','add-expense'))+`<div class="stat-grid"><article class="panel stat-card"><span>Saldo do cenário</span><div class="stat-value">${brl(5840-total)}</div><small>R$ 5.840,00 de entradas de exemplo</small></article><article class="panel stat-card"><span>Saídas registradas</span><div class="stat-value">${brl(total)}</div><small>${state.expenses.length} lançamentos demonstrativos</small></article><article class="panel stat-card"><span>Reserva de tranquilidade</span><div class="stat-value">R$ 8.500</div><small>Um objetivo do cenário de exemplo</small></article></div><div class="two-columns"><article class="panel"><div class="section-heading"><h2>Pequenas escolhas, ao longo do tempo</h2><span class="tag">ILUSTRATIVO</span></div><div class="finance-chart" role="img" aria-label="Gráfico ilustrativo de despesas de abril a setembro, sem dados bancários reais">${['Abr','Mai','Jun','Jul','Ago','Set'].map((m,i)=>`<div class="chart-column"><div class="chart-bar" style="--height:${[64,87,55,72,46,39][i]}%"></div><span>${m}</span></div>`).join('')}</div><p class="description" style="margin-bottom:0">O contexto importa mais que um número isolado. Aqui, a Órbita pode ajudar a perceber padrões.</p></article><article class="panel"><h2>Últimos movimentos</h2>${state.expenses.slice().reverse().map(e=>`<div class="list-row"><span class="quick-icon peach-bg">${icon(e.icon)}</span><div><strong>${escape(e.name)}</strong><small>${escape(e.category)}</small></div><span class="money-value">${brl(e.value)}</span></div>`).join('')}</article></div><div class="notice">Os lançamentos novos existem apenas nesta sessão do protótipo. Não há importação de extrato nem conexão bancária.</div>`;}
  function expenseForm(){openDialog('Um gasto, sem complicar.',`<form id="expense-form"><label class="field">Descrição<input name="name" required maxlength="80" placeholder="Ex.: Café da tarde"></label><label class="field">Valor em reais<input name="value" type="number" min="0.01" max="1000000" step="0.01" required placeholder="0,00"></label><label class="field">Categoria<select name="category"><option>Alimentação</option><option>Casa</option><option>Trabalho</option><option>Lazer</option><option>Outros</option></select></label><div class="notice">O valor será adicionado somente aos dados demonstrativos desta sessão.</div><div class="form-actions"><button type="button" class="button secondary" data-action="close-dialog">Cancelar</button><button class="button primary" type="submit">Registrar no protótipo</button></div></form>`);$('#expense-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),name=f.get('name').trim(),value=Number(f.get('value'));if(!name||!Number.isFinite(value)||value<=0)return;state.expenses.push({name,value,category:f.get('category'),icon:'wallet'});closeDialog();renderFinance();toast('Gasto adicionado ao cenário de exemplo.');});}

  const connectors=[{id:'calendar',name:'Google Calendar',letter:'31',text:'Compromissos que ganham contexto no seu dia.',scope:'Leitura de agenda e propostas de eventos. Eventos novos pedem sua confirmação.'},{id:'mail',name:'Gmail',letter:'M',text:'Mensagens importantes, sem viver na caixa de entrada.',scope:'Leitura e rascunhos. Nenhuma mensagem é enviada sem uma aprovação.'},{id:'notion',name:'Notion',letter:'N',text:'Suas notas e projetos perto de cada conversa.',scope:'Leitura das páginas que você escolher compartilhar.'},{id:'home',name:'Home Assistant',letter:'⌂',text:'O ambiente da casa acompanhando o seu momento.',scope:'Luzes e cenas; ações sensíveis sempre exigem aprovação.'},{id:'slack',name:'Slack',letter:'#',text:'O contexto do trabalho, sem o ruído de todos os canais.',scope:'Canais selecionados. Envio de mensagens sujeito à sua aprovação.'},{id:'whatsapp',name:'WhatsApp',letter:'W',text:'Conversas que importam, com um próximo passo claro.',scope:'Mensagens e rascunhos de exemplo. Nenhum número real é usado.'}];
  function renderConnections(){$('#view-conexoes').innerHTML=viewHeading('TUDO MAIS PERTO. VOCÊ NO CONTROLE','Seu universo conectado','Escolha o que entra na conversa. Cada conexão tem um limite claro.')+`<div class="three-columns">${connectors.map(c=>`<article class="panel connector-card"><div class="connector-top"><span class="connector-logo">${c.letter}</span><span class="tag ${state.connections[c.id]?'green':''}">${state.connections[c.id]?'Conectado na demo':'Não conectado'}</span></div><h3>${c.name}</h3><p>${c.text}</p><button class="button secondary" data-connector="${c.id}">${icon(state.connections[c.id]?'sliders':'plus')}${state.connections[c.id]?'Gerenciar conexão':'Explorar conexão'}</button></article>`).join('')}</div><div class="notice">Os estados de conexão são fictícios. Este protótipo não inicia OAuth, não acessa contas e não solicita credenciais.</div>`;}
  function connectorDetail(id){const c=connectors.find(c=>c.id===id);openDialog(c.name,`<p class="dialog-description">${c.text}</p><div class="notice"><strong>O que a Órbita poderia acessar</strong><br>${c.scope}</div><p class="dialog-description">No produto integrado, você escolheria as permissões antes de autorizar o acesso. Aqui, o botão muda apenas o estado visual.</p><div class="form-actions"><button class="button secondary" data-action="close-dialog">Voltar</button><button class="button primary" data-toggle-connector="${id}">${state.connections[id]?'Desconectar na demo':'Simular conexão'}</button></div>`);}
  function renderSettings(){$('#view-ajustes').innerHTML=viewHeading('NENHUMA PRESENÇA É IGUAL','Do seu jeito','A experiência se adapta ao seu ritmo, não o contrário.')+`<div class="two-columns"><article class="panel"><h2>A presença da Órbita</h2><div class="setting-row"><div><strong>Aparência</strong><p>Mineral durante o dia. Floresta para desacelerar.</p></div><select id="theme-select" aria-label="Tema"><option value="light" ${state.theme==='light'?'selected':''}>Mineral claro</option><option value="dark" ${state.theme==='dark'?'selected':''}>Floresta escuro</option></select></div><div class="setting-row"><div><strong>Movimento reduzido</strong><p>O núcleo permanece estático e os estados usam forma e texto.</p></div><button class="switch" role="switch" aria-label="Movimento reduzido nas preferências" aria-checked="${state.reduced}" data-action="reduce-motion"></button></div><div class="setting-row"><div><strong>Uma identidade que respira</strong><p>Explore os dez estados e a intensidade do núcleo.</p></div><button class="text-button" data-action="lab">Experimentar ${icon('arrow-right')}</button></div><div class="setting-row"><div><strong>Proatividade com delicadeza</strong><p>Exibir sugestões contextuais na visão geral.</p></div><button class="switch" role="switch" aria-checked="${state.proactivity}" aria-label="Sugestões proativas" data-action="proactivity"></button></div></article><article class="panel"><h2>Seu espaço, suas escolhas</h2><div class="setting-row"><div><strong>Modo local</strong><p>Preferência visual do protótipo. Nenhum serviço está conectado.</p></div><button class="switch" role="switch" aria-checked="${state.privacy}" aria-label="Modo local" data-action="toggle-privacy"></button></div><div class="setting-row"><div><strong>Memórias sob seu controle</strong><p>Veja a fonte, corrija ou esqueça o que precisar.</p></div><button class="text-button" data-goto="memoria">Revisar ${icon('arrow-right')}</button></div><div class="setting-row"><div><strong>Suas notas do protótipo</strong><p>Exportar as memórias visíveis em um arquivo JSON.</p></div><button class="text-button" data-action="export">Exportar ${icon('download')}</button></div><div class="notice">Tema, movimento, intensidade e memórias ficam salvos neste navegador. Conversas, rotinas, casa e finanças são reiniciadas ao recarregar.</div></article></div><article class="panel" style="margin-top:22px"><span class="eyebrow">A IDEIA POR TRÁS DA PROPOSTA</span><h2 style="margin-top:10px">Tecnologia presente. Vida em primeiro plano.</h2><p class="description">Órbita Presença troca o painel técnico por espaços de contexto: conversar, lembrar, criar rituais e cuidar da casa. Verde profundo traz estabilidade; menta sinaliza vida; névoa e argila ajudam a orientar sem disputar atenção.</p>${button('Conhecer a proposta','about','orbit','secondary')}</article>`;$('#theme-select').addEventListener('change',e=>{state.theme=e.target.value;updateTheme();});}

  function renderActivity(){const target=$('#activity-content');target.innerHTML=`<p class="drawer-intro">Um lugar para entender os passos da Órbita e escolher o que pode acontecer depois.</p>${state.approved===null?`<article class="approval-card"><span class="eyebrow">ESPERANDO SUA DECISÃO</span><h3>Reservar um espaço para conversar?</h3><p>Um convite de exemplo foi preparado. Confira o destinatário, o horário e o conteúdo.</p><div class="approval-preview"><strong>Para:</strong> Marina · contato fictício<br><strong>Quando:</strong> 21/09, às 14:00 · 30 min<br><strong>Assunto:</strong> Próximos passos da Órbita<br><br>Vamos conversar sobre a nova identidade e alinhar o próximo experimento?</div><div class="form-actions"><button class="button primary" data-action="approve">${icon('check')}Aprovar na demo</button><button class="button secondary" data-action="reject">Agora não</button></div><p style="margin-top:12px;font-size:9px">Nenhum convite real será enviado.</p></article>`:`<div class="notice">${state.approved?'Proposta aprovada na demonstração. Nenhum convite foi enviado.':'Proposta recusada. Você pode continuar no seu ritmo.'}</div>`}<span class="eyebrow">TRILHA DE ATIVIDADE</span>${[...state.activities,{title:'Seu contexto está por aqui',detail:'12 memórias de exemplo preparadas para explorar.',icon:'network'},{title:'Um dia com mais espaço',detail:'Agenda demonstrativa pronta para seu briefing.',icon:'sun'}].slice(0,10).map(a=>`<div class="activity-item"><span>${icon(a.icon)}</span><div><strong>${escape(a.title)}</strong><p>${escape(a.detail)}</p><small>Nesta demonstração</small></div></div>`).join('')}`;}
  function activity(){renderActivity();$('#activity-dialog').showModal();setOrb(state.approved===null?'attention':'idle');}
  function briefing(){openDialog('Seu dia merece um pouco de espaço.',`<p class="dialog-description">Um resumo demonstrativo para começar com clareza.</p><div class="detail-list"><div><span>${icon('calendar')}</span><div><strong>Dois momentos na agenda</strong><p>14:00 · Alinhamento de projeto.<br>16:00 · Um espaço para criar, sem interrupções.</p></div></div><div><span>${icon('network')}</span><div><strong>Uma ideia esperando por você</strong><p>A anotação sobre interfaces calmas combina com a proposta de hoje.</p></div></div><div><span>${icon('leaf')}</span><div><strong>Você não precisa resolver tudo agora</strong><p>Escolha uma prioridade. O resto pode esperar sua vez.</p></div></div></div><div class="form-actions"><button class="button secondary" data-action="briefing-chat">Continuar na conversa</button><button class="button primary" data-action="focus">${icon('spark')}Reservar meu momento</button></div>`);setOrb('speaking');}
  function about(){openDialog('Órbita. Uma presença para a vida.',`<p class="dialog-description">Conceito 01 · Presença<br>Uma nova direção de identidade e experiência para avaliar antes da implementação no produto.</p><div class="detail-list"><div><span>${icon('orbit')}</span><div><strong>Uma identidade viva</strong><p>Presença 3D translúcida, órbitas delicadas e veios orgânicos com profundidade. Dez reações mudam ritmo, luz e forma, mantendo a suavidade da interface.</p></div></div><div><span>${icon('network')}</span><div><strong>Contexto no momento certo</strong><p>Memórias com fonte, sugestões explicáveis e espaços claros para casa, reuniões, finanças e rotinas.</p></div></div><div><span>${icon('shield')}</span><div><strong>Você no centro das decisões</strong><p>Aprovações legíveis, integrações com escopo e um modo foco que protege seu tempo.</p></div></div></div><div class="notice">HTML, CSS e JavaScript locais. Sem dependências, serviços externos, acesso ao microfone ou uso das suas contas. Respostas, agendas, reuniões e saldos são demonstrativos.</div><div class="form-actions"><button class="button primary" data-action="open-lab-from-about">Experimentar a identidade ${icon('arrow-right')}</button></div>`);}

  function voiceDemo(){
    if(state.busy)stopChat();stopDemo();closeDialog();setOrb('listening');toast('Demonstração de voz iniciada. O microfone continua desligado.');
    $('#voice-label').textContent='Demonstração em andamento';
    later(()=>{setOrb('thinking');$('#orb-description').textContent='Pedido de exemplo: “Órbita, como está meu dia?”';},2300);
    later(()=>{setOrb('speaking');$('#orb-title').textContent='Um dia com espaço para você.';$('#orb-description').textContent='Dois compromissos, uma ideia para retomar e um momento de foco.';},4300);
    later(()=>{setOrb('success');$('#voice-label').textContent='Conversar com a Órbita';},7400);
    later(()=>setOrb('idle'),9400);
  }
  function demoSequence(){if(state.busy)stopChat();stopDemo();const seq=['idle','listening','thinking','searching','connecting','executing','speaking','attention','success','error','idle'];seq.forEach((s,i)=>later(()=>setOrb(s),i*2200));toast('Percorrendo dez operações do núcleo holográfico.');}
  function openLab(){closeMenu();if(state.view!=='inicio')navigate('inicio');$('#lab-dialog').showModal();$('#lab-dialog').scrollTop=0;setOrb(orb.state);}
  function formatTime(total){return`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`;}
  function openFocus(){
    closeDialog();$$('dialog[open]').forEach(d=>d.close());state.focusTrigger=document.activeElement;
    $('#focus-overlay').hidden=false;$('#focus-stage-slot').append($('#orb-stage'));
    $('.app-shell').inert=true;$('#sidebar').inert=true;document.body.style.overflow='hidden';
    $('#focus-overlay').focus();orb.resize();updateFocusTimer();
  }
  function closeFocus(){
    $('#presence-card').insertBefore($('#orb-stage'),$('.presence-copy'));
    $('#focus-overlay').hidden=true;$('.app-shell').inert=false;$('#sidebar').inert=false;document.body.style.overflow='';orb.resize();
    if(state.focusTrigger?.isConnected)state.focusTrigger.focus();
  }
  function updateFocusTimer(){if(state.focusRunning)state.focusSeconds=Math.max(0,Math.ceil((state.focusDeadline-Date.now())/1000));$('#focus-timer').textContent=formatTime(state.focusSeconds);$('#focus-start').innerHTML=icon(state.focusRunning?'pause':'play')+(state.focusRunning?'Pausar meu momento':state.focusSeconds===1500?'Começar meu momento':state.focusSeconds===0?'Mais um momento':'Retomar meu momento');if(state.focusRunning&&state.focusSeconds===0){clearInterval(state.focusInterval);state.focusRunning=false;setOrb('success');toast('Seu momento de foco terminou. Que tal uma pausa?');updateFocusTimer();}}
  function toggleFocusTimer(){if(state.focusRunning){updateFocusTimer();state.focusRunning=false;clearInterval(state.focusInterval);}else{if(state.focusSeconds===0)state.focusSeconds=1500;state.focusRunning=true;state.focusDeadline=Date.now()+state.focusSeconds*1000;state.focusInterval=setInterval(updateFocusTimer,250);}updateFocusTimer();}
  function resetFocus(){clearInterval(state.focusInterval);state.focusRunning=false;state.focusSeconds=1500;updateFocusTimer();}

  const searchItems=[...Object.entries(names).map(([id,title])=>({title,detail:'Espaço do seu universo',view:id,icon:id==='casa'?'home':id==='memoria'?'network':'orbit'})),{title:'Modo foco',detail:'Uma coisa de cada vez, com temporizador',action:'focus',icon:'spark'},{title:'Laboratório de animações',detail:'Explore dez estados da presença',action:'lab',icon:'sliders'},{title:'Aprovações e atividade',detail:'Você decide antes de agir',action:'activity',icon:'shield'}];
  function renderSearch(){const query=$('#global-search').value.toLocaleLowerCase('pt-BR');const entries=[...searchItems,...state.memories.map(m=>({title:m.title,detail:`Memória · ${m.type}`,memory:m.id,icon:'network'}))].filter(i=>(i.title+' '+i.detail).toLocaleLowerCase('pt-BR').includes(query)).slice(0,12);$('#search-results').innerHTML=entries.length?entries.map(i=>`<button class="search-result" ${i.view?`data-search-view="${i.view}"`:i.memory?`data-search-memory="${i.memory}"`:`data-search-action="${i.action}"`}>${icon(i.icon)}<span><strong>${escape(i.title)}</strong><small>${escape(i.detail)}</small></span><span>↵</span></button>`).join(''):'<div class="empty-state">Nenhum resultado. Tente “foco”, “memória” ou “casa”.</div>';}
  function openSearch(){$('#global-search').value='';renderSearch();$('#search-dialog').showModal();$('#global-search').focus();}

  const actions={
    menu:()=>{$('#sidebar').classList.add('open');$('#mobile-scrim').classList.add('open');},
    search:openSearch,'close-search':()=>$('#search-dialog').close(),
    theme:()=>{state.theme=state.theme==='light'?'dark':'light';updateTheme();if(state.view==='ajustes')renderSettings();},
    lab:openLab,'close-lab':()=>$('#lab-dialog').close(),'open-lab-from-about':()=>{closeDialog();openLab();},
    'close-dialog':closeDialog,'close-activity':()=>$('#activity-dialog').close(),
    'demo-sequence':demoSequence,'reduce-motion':()=>{state.reduced=!state.reduced;updateReduced();if(state.view==='ajustes')renderSettings();},
    'dismiss-toast':()=>$('#toast').classList.remove('show'),
    focus:openFocus,'close-focus':closeFocus,'focus-timer':toggleFocusTimer,'focus-reset':resetFocus,
    voice:voiceDemo,write:()=>{navigate('conversa');setTimeout(()=>$('#chat-input')?.focus(),80);},
    briefing,'briefing-chat':()=>{closeDialog();navigate('conversa');setTimeout(()=>sendMessage('Como está meu dia?'),50);},
    about,activity,profile:()=>navigate('ajustes'),personalize:()=>{openDialog('Deixe o seu espaço mais seu.',`<p class="dialog-description">Escolha os atalhos que aparecem na visão geral.</p><form id="personalize-form">${['Sua segunda memória','Uma casa que acompanha','O cotidiano, mais leve'].map((t,i)=>`<label class="checkbox-row"><input type="checkbox" name="card" value="${i}" ${$$('.quick-card')[i].hidden?'':'checked'}>${t}</label>`).join('')}<div class="form-actions"><button class="button primary" type="submit">Salvar nesta sessão</button></div></form>`);$('#personalize-form').addEventListener('submit',e=>{e.preventDefault();const chosen=new FormData(e.target).getAll('card');$$('.quick-card').forEach((card,i)=>card.hidden=!chosen.includes(String(i)));closeDialog();toast('Seus atalhos foram personalizados.');});},
    'memory-recall':()=>openDialog('Talvez estas ideias se encontrem.',`<p class="dialog-description">Ontem, você anotou que uma boa ferramenta devolve atenção. Hoje, o projeto pede uma interface mais calma.</p><div class="detail-list"><div><span>${icon('file')}</span><div><strong>“Uma ideia para a Órbita”</strong><p>Uma presença que entende o seu ritmo. Memória demonstrativa.</p></div></div><div><span>${icon('link')}</span><div><strong>“Próximos passos do projeto”</strong><p>Uma identidade orgânica e menos interrupções. Fonte demonstrativa.</p></div></div></div><div class="notice">A proposta é tornar cada sugestão explicável: mostrar o que se conectou e permitir que você confirme ou descarte.</div><div class="form-actions"><button class="button secondary" data-action="close-dialog">Deixar para depois</button><button class="button primary" data-action="project-chat">Pensar sobre isso ${icon('arrow-right')}</button></div>`),
    'add-memory':()=>memoryForm(),
    'memory-view':()=>{state.memoryMode=state.memoryMode==='cards'?'graph':'cards';renderMemory();},
    'new-chat':()=>{if(state.busy)stopChat();state.messages=[{role:'assistant',text:'Um novo espaço para pensar. O que você quer explorar agora?',card:'welcome'}];state.lastAnswer='';state.attachment='';renderChat();},
    'current-chat':()=>$('#chat-input')?.focus(),
    'project-chat':()=>{closeDialog();navigate('conversa');setTimeout(()=>sendMessage('Vamos retomar minha ideia para a Órbita'),50);},
    'home-chat':()=>{navigate('conversa');setTimeout(()=>sendMessage('Como minha casa pode acompanhar meu ritmo?'),50);},
    'save-answer':()=>{const text=state.lastAnswer||state.messages.filter(m=>m.role==='assistant'&&!m.typing).at(-1)?.text;if(!text)return;state.memories.unshift({id:crypto.randomUUID(),title:'Uma ideia da conversa',type:'Ideia',body:text,source:'Conversa demonstrativa',confidence:'Guardada por você'});persist();updateCounts();toast('Resposta demonstrativa guardada como memória.');},
    'read-answer':()=>{if(!('speechSynthesis'in window)){toast('Este navegador não oferece leitura em voz.');return;}const text=state.lastAnswer;if(!text){toast('Envie uma mensagem primeiro para ouvir a resposta.');return;}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='pt-BR';utterance.rate=1;utterance.onstart=()=>setOrb('speaking');utterance.onend=()=>setOrb('idle');utterance.onerror=()=>{setOrb('idle');toast('A voz não está disponível neste navegador.');};speechSynthesis.speak(utterance);toast('Lendo com a voz do navegador. Pressione Esc para parar.');},
    attach:()=>{const input=document.createElement('input');input.type='file';input.addEventListener('change',()=>{if(input.files?.[0]){state.attachment=input.files[0].name;renderAttachment();toast('Somente o nome será exibido. O arquivo não é lido nem enviado.');}});input.click();},
    'remove-attachment':()=>{state.attachment='';renderAttachment();},
    'add-routine':routineForm,'add-expense':expenseForm,
    'meeting-toggle':toggleMeeting,'meeting-summary':()=>{state.meetingSummary=true;renderMeetingSummary();$('#meeting-summary-slot')?.scrollIntoView({behavior:state.reduced?'instant':'smooth',block:'center'});},
    'meeting-detail':()=>openDialog('Alinhamento de projeto.',`<p class="dialog-description">Hoje, 14:00 · 45 minutos<br>Você e Marina · Participantes fictícios</p><div class="notice"><strong>O que vale levar para a conversa</strong><br>A proposta de identidade, os estados da Órbita e uma ideia de como simplificar a navegação.</div><div class="form-actions"><button class="button primary" data-action="goto-meetings">Explorar a reunião ${icon('arrow-right')}</button></div>`),
    'goto-meetings':()=>{closeDialog();navigate('reunioes');},
    'save-meeting':()=>{if(state.memories.some(m=>m.id==='meeting-decisions')){toast('Estas decisões já estão na memória.');return;}state.memories.unshift({id:'meeting-decisions',title:'Decisões: nova presença da Órbita',type:'Projeto',body:'Explorar identidade orgânica, diferenciar estados por movimento e validar o protótipo no celular.',source:'Reunião demonstrativa',confidence:'Resumo do roteiro de exemplo'});persist();updateCounts();toast('Decisões da demonstração guardadas na memória.');},
    'find-object':()=>openDialog('Talvez esteja bem perto.',`<p class="dialog-description">Na cena de exemplo, a chave foi vista por último na mesa da sala às 10:42.</p><div class="notice"><strong>O que a interface deveria mostrar</strong><br>Último local observado, horário e grau de confiança. Uma observação anterior não é garantia de localização atual.<br><br>Não há câmeras nem imagens reais conectadas a este protótipo.</div><div class="form-actions"><button class="button primary" data-action="close-dialog">Entendi</button></div>`),
    'door-approval':()=>openDialog('Abrir a porta de entrada?',`<p class="dialog-description">Uma ação sensível merece uma escolha explícita. Confira o dispositivo e quem pediu antes de continuar.</p><div class="notice"><strong>Dispositivo:</strong> Porta de entrada fictícia<br><strong>Solicitante:</strong> Wesley · cenário de demonstração<br><strong>Efeito:</strong> Liberar a fechadura<br><br>Nenhuma fechadura está conectada.</div><div class="form-actions"><button class="button secondary" data-action="close-dialog">Manter fechada</button><button class="button primary" data-action="door-confirm">Simular aprovação</button></div>`),
    'door-confirm':()=>{closeDialog();setOrb('success');toast('Aprovação demonstrada. Nenhuma porta real foi aberta.');log('Ação sensível revisada','Simulação da aprovação de abertura da porta.','lock');},
    approve:()=>{state.approved=true;$('#notification-dot').hidden=true;setOrb('success');log('Você aprovou a proposta','Aprovação local. Nenhum convite enviado.');renderActivity();toast('Aprovação registrada na demonstração.');},
    reject:()=>{state.approved=false;$('#notification-dot').hidden=true;setOrb('idle');log('Você escolheu deixar para depois','A proposta foi recusada sem efeitos externos.','shield');renderActivity();},
    privacy:()=>openDialog('Seu universo continua seu.',`<p class="dialog-description">Nesta proposta, a privacidade aparece no momento da escolha e no contexto de cada ação.</p><div class="detail-list"><div><span>${icon('shield')}</span><div><strong>Local por escolha</strong><p>Você escolhe quando uma conexão externa faz sentido.</p></div></div><div><span>${icon('network')}</span><div><strong>Uma memória que você pode revisar</strong><p>Veja fontes, corrija informações e esqueça o que não precisa ficar.</p></div></div><div><span>${icon('check')}</span><div><strong>Ações sensíveis passam por você</strong><p>A interface mostra destino, conteúdo e efeito antes de uma aprovação.</p></div></div></div><div class="notice">Este HTML é independente do produto. Nenhum serviço, conta ou microfone está conectado.</div>`),
    'toggle-privacy':()=>{state.privacy=!state.privacy;$('#privacy-label').textContent=state.privacy?'Local por escolha':'Modo flexível · demo';renderSettings();},
    proactivity:()=>{state.proactivity=!state.proactivity;$('.insight-card').hidden=!state.proactivity;renderSettings();},
    export:()=>{const blob=new Blob([JSON.stringify({prototype:'Órbita Presença',note:'Memórias demonstrativas e notas criadas no protótipo',memories:state.memories},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='orbita-presenca-memorias.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Suas memórias do protótipo foram exportadas.');},
  };

  document.addEventListener('click',e=>{
    const el=e.target.closest('button,a');if(!el)return;
    if(el.dataset.action){
      // Save/read the selected response, even when newer messages exist.
      if(['save-answer','read-answer'].includes(el.dataset.action)&&el.closest('.message')){
        const index=$$('.message',$('#chat-messages')).indexOf(el.closest('.message'));
        state.lastAnswer=state.messages[index]?.text||'';
      }
      actions[el.dataset.action]?.();return;
    }
    if(el.dataset.goto){navigate(el.dataset.goto);return;}
    if(el.dataset.state){stopDemo();if(state.busy)stopChat();setOrb(el.dataset.state);return;}
    if(el.dataset.prompt){sendMessage(el.dataset.prompt);return;}
    if(el.dataset.memoryFilter){state.memoryFilter=el.dataset.memoryFilter;renderMemory();return;}
    if(el.dataset.memory){memoryForm(state.memories.find(m=>m.id===el.dataset.memory));return;}
    if(el.dataset.deleteMemory){const id=el.dataset.deleteMemory;const memory=state.memories.find(m=>m.id===id);if(!memory)return;openDialog('Deixar essa memória ir?',`<p class="dialog-description">“${escape(memory.title)}” será removida das memórias deste protótipo.</p><div class="form-actions"><button class="button secondary" data-action="close-dialog">Manter memória</button><button class="button danger" data-confirm-delete="${id}">Esquecer memória</button></div>`);return;}
    if(el.dataset.confirmDelete){state.memories=state.memories.filter(m=>m.id!==el.dataset.confirmDelete);persist();updateCounts();closeDialog();renderMemory();toast('Memória removida deste protótipo.');return;}
    if(el.dataset.routineToggle){const r=state.routines.find(r=>r.id===el.dataset.routineToggle);r.active=!r.active;renderRoutines();updateCounts();return;}
    if(el.dataset.runRoutine){runRoutine(el.dataset.runRoutine);return;}
    if(el.dataset.roomLight){const r=state.rooms.find(r=>r.id===el.dataset.roomLight);r.light=!r.light;renderHome();return;}
    if(el.dataset.scene){applyScene(el.dataset.scene);return;}
    if(el.dataset.connector){connectorDetail(el.dataset.connector);return;}
    if(el.dataset.toggleConnector){const id=el.dataset.toggleConnector;state.connections[id]=!state.connections[id];closeDialog();renderConnections();setOrb(state.connections[id]?'connecting':'idle');toast(state.connections[id]?'Conexão simulada. Nenhum acesso externo foi autorizado.':'Conexão desativada na demonstração.');return;}
    if(el.dataset.searchView){$('#search-dialog').close();navigate(el.dataset.searchView);return;}
    if(el.dataset.searchMemory){$('#search-dialog').close();navigate('memoria');memoryForm(state.memories.find(m=>m.id===el.dataset.searchMemory));return;}
    if(el.dataset.searchAction){$('#search-dialog').close();actions[el.dataset.searchAction]?.();}
  });
  document.addEventListener('input',e=>{if(e.target.dataset.brightness){const r=state.rooms.find(r=>r.id===e.target.dataset.brightness);r.brightness=Number(e.target.value);$(`#output-${r.id}`).textContent=`${r.brightness}%`;}});
  $('#intensity').addEventListener('input',e=>{state.intensity=Number(e.target.value);[orb,labOrb].forEach(o=>{o.intensity=state.intensity/100;o.dirty=true;o.schedule();});$('#intensity-value').textContent=`${state.intensity}%`;persist();});
  $('#global-search').addEventListener('input',renderSearch);
  $('#global-search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('.search-result')?.click();}if(e.key==='ArrowDown'){e.preventDefault();$('.search-result')?.focus();}});
  $('#mobile-scrim').addEventListener('click',closeMenu);
  $$('dialog').forEach(dialog=>dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();}));
  $('#lab-dialog').addEventListener('close',()=>{stopDemo();if(!state.busy&&!state.meetingRunning)setOrb('idle');$('#voice-label').textContent='Conversar com a Órbita';});
  $('#detail-dialog').addEventListener('close',()=>{if($('#routine-progress')){stopDemo();setOrb('idle');}});
  document.addEventListener('keydown',e=>{
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if($('#focus-overlay').hidden)openSearch();}
    if(e.key==='Escape'){closeMenu();stopDemo();if('speechSynthesis'in window)speechSynthesis.cancel();if(!$('#focus-overlay').hidden){closeFocus();e.preventDefault();}if(!state.busy&&!state.meetingRunning)setOrb('idle');$('#voice-label').textContent='Conversar com a Órbita';}
    if(e.key==='Tab'&&!$('#focus-overlay').hidden){const items=$$('button:not([disabled]),[tabindex="0"]', $('#focus-overlay'));const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('#focus-overlay'))){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
  });
  addEventListener('hashchange',()=>renderView(location.hash.slice(1)));
  addEventListener('pagehide',()=>{stopDemo();clearInterval(state.meetingInterval);clearInterval(state.focusInterval);state.chatTimers.forEach(clearTimeout);state.chatTimers.forEach(clearInterval);if('speechSynthesis'in window)speechSynthesis.cancel();});
  $('#state-controls').innerHTML=Object.entries(states).map(([id,cfg])=>`<button class="state-button" data-state="${id}" aria-pressed="${id==='idle'}">${icon(cfg.icon)}${cfg.label}</button>`).join('');
  $('.drawer-intro',$('#lab-dialog')).textContent='Uma presença que respira, se concentra e se expressa. Explore dez reações: impulsos percorrem os veios, a membrana responde e o gesto aproxima. Mova o cursor ou toque na esfera.';
  $('.coordinate-left').textContent='MOVA / CLIQUE';$('.coordinate-right').textContent='NEURAL CORE';
  $('#intensity').value=state.intensity;$('#intensity-value').textContent=`${state.intensity}%`;orb.intensity=labOrb.intensity=state.intensity/100;
  hydrate();updateTheme();updateReduced();updateCounts();setOrb('idle');renderView(location.hash.slice(1)||'inicio');
})();
