"""Verificação de interação e screenshots. Requer Playwright apenas para QA."""
from pathlib import Path
import re
import sys
from playwright.sync_api import sync_playwright, expect

ROOT = Path(__file__).resolve().parent

with sync_playwright() as p:
    browser = p.chromium.launch(channel="chrome", headless=True, args=['--enable-unsafe-swiftshader'])
    page = browser.new_page(viewport={"width": 1440, "height": 1080}, device_scale_factor=1)
    page.set_default_navigation_timeout(60000)
    errors = []
    page.on("pageerror", lambda error: errors.append(str(error)))
    if '--portable-only' in sys.argv:
        page.context.set_offline(True)
        page.goto((ROOT / 'orbita-presenca.html').as_uri(), wait_until='load')
        assert not errors, errors
        expect(page.locator('#state-controls button')).to_have_count(10)
        expect(page.locator('#orb-canvas')).to_have_attribute('data-renderer','webgl')
        expect(page.locator('#orb-title')).to_have_text('O que vamos fazer hoje?')
        page.locator('[data-action="write"]').click()
        expect(page.locator('#chat-input')).to_be_visible()
        page.locator('[data-action="theme"]').click()
        expect(page.locator('html')).to_have_attribute('data-theme','dark')
        assert not errors, errors
        print('PASS: portable single HTML, offline, navigation, theme, zero JS errors', flush=True)
        browser.close()
        sys.exit(0)
    page.goto("http://127.0.0.1:4173", wait_until="networkidle", timeout=60000)
    page.set_default_timeout(15000)
    page.wait_for_selector("#orb-canvas")
    page.wait_for_function("document.querySelector('#orb-canvas').width > 0")
    expect(page.locator('#orb-canvas')).to_have_attribute('data-renderer','webgl')
    expect(page.locator('#orb-canvas')).to_have_attribute('data-identity','neural-organic')
    page.wait_for_timeout(300)
    page.screenshot(path=str(ROOT / "preview-desktop.png"), full_page=True)
    print({"title": page.title(), "errors": errors, "desktopOverflow": page.evaluate("document.documentElement.scrollWidth > innerWidth")}, flush=True)
    page.get_by_role("button", name="Alternar tema").click()
    page.wait_for_timeout(900)
    page.screenshot(path=str(ROOT / "preview-dark.png"), full_page=True)
    page.get_by_role("button", name="Alternar tema").click()
    page.locator('[data-action="lab"]').first.click()
    for mode in ['idle','listening','thinking','speaking','searching','connecting','executing','success','attention','error']:
        page.locator(f'[data-state="{mode}"]').click()
        expect(page.locator('body')).to_have_attribute('data-orb-state', mode)
        expect(page.locator(f'[data-state="{mode}"]')).to_have_attribute('aria-pressed', 'true')
        if '--orb-only' in sys.argv:
            page.wait_for_timeout(350)
            frame = page.locator('#orb-canvas').evaluate('(c) => c.toDataURL()')
            page.wait_for_timeout(1800)
            if frame == page.locator('#orb-canvas').evaluate('(c) => c.toDataURL()'):
                print(page.locator('#orb-canvas').evaluate('(c) => {const o=c.orbitaPresence; return {visible:o.visible,hidden:document.hidden,reduced:o.reduced,lost:o.gl.isContextLost(),frames:o.frameCount,time:o.time,glError:o.gl.getError()};}'), flush=True)
            assert frame != page.locator('#orb-canvas').evaluate('(c) => c.toDataURL()'), f'No motion in {mode}'
            page.locator('#orb-canvas').screenshot(path=str(ROOT / f'preview-orb-{mode}.png'))
    page.locator('[data-action="reduce-motion"]').click()
    page.wait_for_timeout(100)
    first_frame = page.locator('#orb-canvas').evaluate('(c) => c.toDataURL()')
    page.wait_for_timeout(150)
    assert first_frame == page.locator('#orb-canvas').evaluate('(c) => c.toDataURL()'), 'Reduced motion keeps animating'
    page.locator('[data-action="reduce-motion"]').click()
    page.locator('[data-action="close-lab"]').click()
    canvas = page.locator('#orb-canvas')
    canvas.click(position={'x':345,'y':130})
    expect(canvas).to_have_attribute('data-pulse', re.compile(r'\d+'))
    before_pulse = canvas.get_attribute('data-pulse')
    canvas.focus()
    canvas.press('Enter')
    expect(canvas).not_to_have_attribute('data-pulse',before_pulse)
    print('PASS: ten states, selection feedback, reduced motion, pointer and keyboard pulses', flush=True)
    page.evaluate("""() => { window.sourceCounts = []; new MutationObserver(() => window.sourceCounts.push(document.querySelectorAll('#research-panel .source-card').length)).observe(document.querySelector('#research-panel'), {childList:true,subtree:true}); }""")
    page.locator('[data-action="research-demo"]').click()
    expect(page.locator('#research-panel')).to_be_visible()
    expect(page.locator('.day-panel')).not_to_be_visible()
    expect(page.locator('#research-panel .source-card')).to_have_count(3, timeout=6000)
    assert all(count in page.evaluate('window.sourceCounts') for count in [0,1,2,3]), 'Sources did not arrive progressively'
    expect(page.locator('#research-panel')).to_contain_text('Pesquisa concluída')
    assert page.locator('#research-panel .source-card').first.get_attribute('href').startswith('https://developer.mozilla.org/')
    page.screenshot(path=str(ROOT / 'preview-pesquisa.png'), full_page=True)
    page.locator('[data-research-close]').click()
    expect(page.locator('.day-panel')).to_be_visible()
    print('PASS: progressive source cards, real links, completion and dismissal', flush=True)
    if '--orb-only' in sys.argv:
        page.locator('.focus-teaser').click()
        page.wait_for_timeout(400)
        page.screenshot(path=str(ROOT / 'preview-foco.png'), full_page=True)
        page.keyboard.press('Escape')
        page.set_viewport_size({'width':390,'height':844})
        page.wait_for_timeout(250)
        page.screenshot(path=str(ROOT / 'preview-mobile.png'), full_page=True)
        page.locator('[data-action="menu"]').click()
        page.locator('[data-action="lab"]').first.click()
        page.locator('[data-state="executing"]').click()
        page.wait_for_timeout(400)
        box = page.locator('#lab-canvas').bounding_box()
        assert box['y'] >= 0 and box['y'] + box['height'] <= 844
        page.screenshot(path=str(ROOT / 'preview-mobile-lab.png'), full_page=True)
        assert not errors, errors
        print('PASS: organic neural presence, desktop, mobile, focus, zero browser errors', flush=True)
        browser.close()
        sys.exit(0)

    def go(view):
        page.locator(f'.nav-link[data-view="{view}"]').click()
        expect(page.locator(f'#view-{view}')).to_be_visible()

    go('conversa')
    page.locator('#chat-input').fill('Pesquise interfaces 3D no navegador')
    page.locator('#chat-input').press('Enter')
    expect(page.locator('.chat-research .source-card')).to_have_count(3, timeout=8000)
    expect(page.locator('#chat-send')).to_have_attribute('aria-label', 'Enviar mensagem', timeout=20000)
    expect(page.locator('.message').last).to_contain_text('roteirizadas')
    page.screenshot(path=str(ROOT / 'preview-chat-pesquisa.png'), full_page=True)
    page.locator('#chat-input').fill('Busque outra referência')
    page.locator('#chat-input').press('Enter')
    page.locator('#chat-send').click()
    page.wait_for_timeout(1200)
    expect(page.locator('.message').last.locator('.source-card')).to_have_count(0)
    expect(page.locator('.message').last).to_contain_text('Pesquisa interrompida')
    print('PASS: inline chat research, persistent previous sources, cancellation', flush=True)
    page.locator('#chat-input').fill('Como está meu dia?')
    page.locator('#chat-input').press('Enter')
    expect(page.locator('#chat-send')).to_have_attribute('aria-label', 'Parar resposta')
    assert page.locator('.message').first.evaluate('(el) => getComputedStyle(el).opacity') == '1', 'History fades during streaming'
    expect(page.locator('#chat-send')).to_have_attribute('aria-label', 'Enviar mensagem', timeout=15000)
    expect(page.locator('.message-assistant-card')).to_contain_text('Seu dia, com respiro')
    page.locator('#chat-input').fill('Vamos retomar minha ideia para a Órbita')
    page.locator('#chat-input').press('Enter')
    page.locator('#chat-send').click()
    expect(page.locator('.message').last).to_contain_text('interrompida')
    page.screenshot(path=str(ROOT / 'preview-conversa.png'), full_page=True)
    print('PASS: scripted conversation, streamed response, cancellation', flush=True)

    go('memoria')
    page.locator('[data-action="add-memory"]').click()
    page.get_by_label('Título', exact=True).fill('Minha ideia <teste>')
    page.get_by_label('Sua anotação', exact=True).fill('Uma ideia criada durante a verificação do protótipo.')
    page.get_by_role('button', name='Guardar memória', exact=True).click()
    page.locator('#memory-search').fill('Minha ideia')
    expect(page.locator('.memory-card')).to_have_count(1)
    expect(page.locator('.memory-card')).to_contain_text('Minha ideia <teste>')
    page.locator('.memory-card').click()
    page.get_by_label('Título', exact=True).fill('Minha ideia revisada')
    page.get_by_role('button', name='Guardar memória', exact=True).click()
    expect(page.locator('.memory-card')).to_contain_text('Minha ideia revisada')
    page.reload(wait_until='networkidle')
    page.locator('#memory-search').fill('Minha ideia revisada')
    expect(page.locator('.memory-card')).to_have_count(1)
    page.locator('.memory-card').click()
    page.get_by_role('button', name='Esquecer', exact=True).click()
    page.get_by_role('button', name='Esquecer memória', exact=True).click()
    expect(page.locator('.memory-card')).to_have_count(0)
    page.locator('#memory-search').fill('')
    page.locator('[data-memory-filter="Casa"]').click()
    expect(page.locator('.memory-card')).to_have_count(2)
    page.locator('[data-action="memory-view"]').click()
    expect(page.locator('.memory-graph')).to_be_visible()
    page.locator('[data-action="memory-view"]').click()
    page.locator('[data-memory-filter="Tudo"]').click()
    page.screenshot(path=str(ROOT / 'preview-memoria.png'), full_page=True)
    print('PASS: memory create, escaped text, edit, persistence, delete, filter, graph', flush=True)

    go('rotinas')
    page.locator('[data-routine-toggle="r1"]').click()
    expect(page.locator('[data-run-routine="r1"]')).to_be_disabled()
    page.locator('[data-routine-toggle="r1"]').click()
    page.locator('[data-run-routine="r1"]').click()
    expect(page.locator('#routine-step-2')).to_contain_text('Etapa demonstrada', timeout=10000)
    page.locator('#detail-dialog [data-action="close-dialog"]').last.click()
    page.locator('[data-action="add-routine"]').click()
    page.get_by_label('Nome da rotina').fill('Uma pausa de teste')
    page.get_by_label('Qual é a intenção?').fill('Respirar por alguns minutos.')
    page.get_by_role('button', name='Criar rotina de exemplo').click()
    expect(page.locator('.routine-card')).to_have_count(4)
    print('PASS: routine toggle, execution feedback, creation', flush=True)

    go('casa')
    page.locator('[data-scene="noite"]').click()
    for room in ['sala','escritorio','quarto']:
        expect(page.locator(f'[data-room-light="{room}"]')).to_have_attribute('aria-checked', 'false')
    page.locator('[data-scene="criar"]').click()
    expect(page.locator('[data-room-light="escritorio"]')).to_have_attribute('aria-checked', 'true')
    page.locator('[data-action="door-approval"]').click()
    expect(page.locator('#detail-dialog')).to_contain_text('Nenhuma fechadura está conectada.')
    page.locator('[data-action="door-confirm"]').click()
    print('PASS: room scenes and explicit sensitive-action approval', flush=True)

    go('financas')
    page.locator('[data-action="add-expense"]').click()
    page.get_by_label('Descrição', exact=True).fill('Café de teste')
    page.get_by_label('Valor em reais').fill('25')
    page.get_by_role('button', name='Registrar no protótipo').click()
    expect(page.locator('.stat-card').nth(1)).to_contain_text('530,30')
    expect(page.locator('#view-financas')).to_contain_text('Café de teste')
    print('PASS: expense form updates transaction list and calculated total', flush=True)

    go('conexoes')
    page.locator('[data-connector="notion"]').click()
    page.locator('[data-toggle-connector="notion"]').click()
    expect(page.locator('.connector-card').filter(has_text='Notion')).to_contain_text('Conectado na demo')
    page.locator('[data-action="activity"]').click()
    page.locator('[data-action="approve"]').click()
    expect(page.locator('#activity-content')).to_contain_text('Nenhum convite foi enviado.')
    page.locator('[data-action="close-activity"]').click()
    print('PASS: connector permissions, simulated connection, proposal approval', flush=True)

    go('reunioes')
    page.locator('[data-action="meeting-toggle"]').click()
    expect(page.locator('#meeting-summary-slot')).to_contain_text('Uma interface que devolve atenção', timeout=25000)
    expect(page.locator('.transcript-row')).to_have_count(4)
    page.locator('[data-action="save-meeting"]').click()
    page.screenshot(path=str(ROOT / 'preview-reunioes.png'), full_page=True)
    print('PASS: live demo transcript, summary, saving decisions', flush=True)

    page.keyboard.press('Control+k')
    page.locator('#global-search').fill('Modo foco')
    page.locator('#global-search').press('Enter')
    expect(page.locator('#focus-overlay')).to_be_visible()
    expect(page.locator('#focus-stage-slot #orb-canvas')).to_be_visible()
    page.locator('[data-action="focus-timer"]').click()
    expect(page.locator('#focus-timer')).not_to_have_text('25:00')
    page.locator('[data-action="focus-timer"]').click()
    paused = page.locator('#focus-timer').inner_text()
    page.wait_for_timeout(1100)
    expect(page.locator('#focus-timer')).to_have_text(paused)
    page.screenshot(path=str(ROOT / 'preview-foco.png'), full_page=True)
    page.keyboard.press('Escape')
    expect(page.locator('#focus-overlay')).not_to_be_visible()
    expect(page.locator('.app-shell')).not_to_have_attribute('inert','')
    print('PASS: command search, focus mode, timer pause, escape restoration', flush=True)

    page.evaluate("localStorage.removeItem('orbita-presenca-prototype-v1')")
    page.reload(wait_until='networkidle')
    go('inicio')
    page.set_viewport_size({"width": 390, "height": 844})
    page.wait_for_timeout(400)
    page.screenshot(path=str(ROOT / "preview-mobile.png"), full_page=True)
    assert not page.evaluate('document.documentElement.scrollWidth > innerWidth'), 'Mobile overflow'
    # The mobile laboratory has its own preview, so the drawer never hides the orb being evaluated.
    page.locator('[data-action="menu"]').click()
    page.locator('[data-action="lab"]').first.click()
    expect(page.locator('#lab-canvas')).to_be_visible()
    page.locator('[data-state="thinking"]').click()
    page.wait_for_timeout(350)
    preview_box = page.locator('#lab-canvas').bounding_box()
    assert preview_box['y'] >= 0 and preview_box['y'] + preview_box['height'] <= 844, 'Mobile state preview outside viewport'
    page.screenshot(path=str(ROOT / 'preview-mobile-lab.png'), full_page=True)
    page.keyboard.press('Escape')
    for view in ['conversa','memoria','rotinas','casa','reunioes','financas','conexoes','ajustes','inicio']:
        page.locator('[data-action="menu"]').click()
        go(view)
        assert not page.evaluate('document.documentElement.scrollWidth > innerWidth'), f'Overflow on mobile {view}'
    page.set_viewport_size({'width':320,'height':740})
    page.wait_for_timeout(150)
    assert not page.evaluate('document.documentElement.scrollWidth > innerWidth'), '320px overflow'
    print('PASS: all nine mobile views, mobile animation preview, 320px layout', flush=True)

    # Opening the HTML directly must work without a server or network.
    offline = browser.new_context(offline=True, viewport={'width':1280,'height':900})
    file_page = offline.new_page()
    file_page.on('pageerror', lambda error: errors.append(str(error)))
    file_page.goto((ROOT / 'index.html').as_uri(), wait_until='load')
    expect(file_page.locator('#orb-title')).to_have_text('O que vamos fazer hoje?')
    file_page.locator('[data-action="write"]').click()
    expect(file_page.locator('#chat-input')).to_be_visible()
    print('PASS: double-click HTML, offline operation, no external dependencies', flush=True)
    assert not errors, errors
    print({'result':'ALL CHECKS PASSED','browserErrors':errors}, flush=True)
    offline.close()
    browser.close()
